### ISSUE TITLE
assembly failure

### ISSUE THREAD

**Issue by geoHeil** [jiayuasu/GeoSparkTemplateProject#1]
using
```
"org.datasyslab" % "babylon" % "0.2.2",
 "org.datasyslab" % "geospark" % "0.9.1",
```
fails the `sbt assembly` task wen building the fat jar due to duplicate classes:

```
assemblyMergeStrategy in assembly := {
  case PathList("META-INF", "MANIFEST.MF") => MergeStrategy.discard
  case PathList("META-INF", "LICENSE") => MergeStrategy.discard
  case PathList("META-INF", "LICENSE.txt") => MergeStrategy.discard
  case PathList("META-INF", "NOTICE") => MergeStrategy.discard
  case PathList("META-INF", "NOTICE.txt") => MergeStrategy.discard
  case PathList("rootdoc.txt") => MergeStrategy.discard
  case PathList("org.datasyslab", "geospark", xs@_*) => MergeStrategy.first
  case _ => MergeStrategy.deduplicate
}
```
is not fixing it

This are all the clashes:

```
error] java.lang.RuntimeException: deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:META-INF/maven/com.fasterxml.jackson.core/jackson-annotations/pom.properties
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:META-INF/maven/com.fasterxml.jackson.core/jackson-annotations/pom.properties
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:META-INF/maven/com.fasterxml.jackson.core/jackson-annotations/pom.xml
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:META-INF/maven/com.fasterxml.jackson.core/jackson-annotations/pom.xml
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:META-INF/services/com.fasterxml.jackson.core.JsonFactory
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:META-INF/services/com.fasterxml.jackson.core.JsonFactory
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonAnySetter.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonAnySetter.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonFormat$Feature.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonFormat$Feature.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonFormat$Features.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonFormat$Features.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonFormat$Shape.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonFormat$Shape.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonFormat$Value.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonFormat$Value.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonIgnoreProperties.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonIgnoreProperties.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonInclude$Include.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonInclude$Include.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonInclude$Value.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonInclude$Value.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonProperty$Access.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonProperty$Access.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonTypeInfo$None.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonTypeInfo$None.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonTypeInfo.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonTypeInfo.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/ObjectIdGenerator$IdKey.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/ObjectIdGenerator$IdKey.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$Base.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$Base.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$IntSequenceGenerator.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$IntSequenceGenerator.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$None.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$None.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$PropertyGenerator.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$PropertyGenerator.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$UUIDGenerator.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$UUIDGenerator.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators.class
[error] 	at sbtassembly.Assembly$.applyStrategies(Assembly.scala:141)
[error] 	at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
[error] 	at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:67)
[error] 	at sbtassembly.Assembly$.inputs$1(Assembly.scala:57)
[error] 	at sbtassembly.Assembly$.apply(Assembly.scala:84)
[error] 	at sbtassembly.Assembly$.$anonfun$assemblyTask$1(Assembly.scala:249)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (*:assembly) deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:META-INF/maven/com.fasterxml.jackson.core/jackson-annotations/pom.properties
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:META-INF/maven/com.fasterxml.jackson.core/jackson-annotations/pom.properties
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:META-INF/maven/com.fasterxml.jackson.core/jackson-annotations/pom.xml
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:META-INF/maven/com.fasterxml.jackson.core/jackson-annotations/pom.xml
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:META-INF/services/com.fasterxml.jackson.core.JsonFactory
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:META-INF/services/com.fasterxml.jackson.core.JsonFactory
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonAnySetter.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonAnySetter.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonFormat$Feature.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonFormat$Feature.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonFormat$Features.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonFormat$Features.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonFormat$Shape.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonFormat$Shape.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonFormat$Value.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonFormat$Value.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonIgnoreProperties.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonIgnoreProperties.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonInclude$Include.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonInclude$Include.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonInclude$Value.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonInclude$Value.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonProperty$Access.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonProperty$Access.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonTypeInfo$None.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonTypeInfo$None.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/JsonTypeInfo.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/JsonTypeInfo.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/ObjectIdGenerator$IdKey.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/ObjectIdGenerator$IdKey.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$Base.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$Base.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$IntSequenceGenerator.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$IntSequenceGenerator.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$None.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$None.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$PropertyGenerator.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$PropertyGenerator.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$UUIDGenerator.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators$UUIDGenerator.class
[error] deduplicate: different file contents found in the following:
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/babylon/jars/babylon-0.2.2.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators.class
[error] /Users/geoheil/.ivy2/cache/org.datasyslab/geospark/jars/geospark-0.9.1.jar:com/fasterxml/jackson/annotation/ObjectIdGenerators.class
```

**Comment by geoHeil** [comment]
```
libraryDependencies += "org.datasyslab" % "babylon" % "0.2.2" excludeAll (
  ExclusionRule(organization = "jackson"))
```
does not seem to fix it

**Comment by jiayuasu** [comment]
This has been solved in the latest template.
