### ISSUE TITLE
Manifest error

### ISSUE THREAD

**Issue by codejoy** [jiayuasu/GeoSparkTemplateProject#3]
I am not sure what I am doing wrong, following the instructions to build the geospark-sql demo and I get a manifest error when I try to spark submit it after it successfully does a sbt assembly.

straight from git clone didn't modify anything and this is on 
Spark V 2.2.0
and Scala version 2.11.8
Java 64 bit 1.8.0_91

spark-submit GeoSparkSQLScalaTemplate-assembly-0.1.0.jar 
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:284)
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:238)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:273)
	at java.util.jar.JarVerifier.update(JarVerifier.java:228)
	at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
	at java.util.jar.JarFile.getInputStream(JarFile.java:450)
	at sun.misc.JarIndex.getJarIndex(JarIndex.java:137)
	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:839)
	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:831)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.misc.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:830)
	at sun.misc.URLClassPath$JarLoader.<init>(URLClassPath.java:803)
	at sun.misc.URLClassPath$3.run(URLClassPath.java:530)
	at sun.misc.URLClassPath$3.run(URLClassPath.java:520)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.misc.URLClassPath.getLoader(URLClassPath.java:519)
	at sun.misc.URLClassPath.getLoader(URLClassPath.java:492)
	at sun.misc.URLClassPath.getNextLoader(URLClassPath.java:457)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:211)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:230)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:712)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by jiayuasu** [comment]
If you want to use ./bin/spark-submit, you must change the dependency packaging scope from "compile" to "provided". Otherwise, sbt will package Spark itself into your fat jar and eventually lead to version conflicts.

Just simply change this file: https://github.com/jiayuasu/GeoSparkTemplateProject/blob/master/geospark-sql/scala/build.sbt

**Comment by YaboSun** [comment]
I am a beginner, and  I am confused whether I need to compile and package before I run template projects locally
straight git clone , import to IntelliJ IDEA and add GeoSpark and Babylon dependencies then build and run the geospark/java/main/Example on
Spark 2.2.1 
Scala 2.11.12 
Java 64bit 1.8._151
Exception in thread "main" java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapred.FileInputFormat
	at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:312)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:199)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1.apply(RDD.scala:1115)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.aggregate(RDD.scala:1108)
	at org.apache.spark.api.java.JavaRDDLike$class.aggregate(JavaRDDLike.scala:426)
	at org.apache.spark.api.java.AbstractJavaRDDLike.aggregate(JavaRDDLike.scala:45)
	at org.datasyslab.geospark.spatialRDD.SpatialRDD.analyze(SpatialRDD.java:430)
	at org.datasyslab.geospark.spatialRDD.SpatialRDD.analyze(SpatialRDD.java:404)
	at org.datasyslab.geospark.spatialRDD.PointRDD.<init>(PointRDD.java:300)
	at example.Example.testSpatialRangeQuery(Example.java:156)
	at example.Example.main(Example.java:128)

**Comment by jiayuasu** [comment]
@YaboSun This is because of Spark's dependency conflict. This is an expected error.

1. To run this project in IDE, do not change anything and DO NOT PACKAGE.
2. To run this in cluster mode, you have to package this project to get the JAR. But before, package the project, you need to change the dependency scope.

Details are here: http://datasystemslab.github.io/GeoSpark/download/project/
