### ISSUE TITLE
IllegalAccessError

### ISSUE THREAD

**Issue by YaboSun** [jiayuasu/GeoSparkTemplateProject#4]
I am a beginner, and  I am confused whether I need to compile and package before I run template projects locally
straight git clone , import to IntelliJ IDEA and add GeoSpark and Babylon dependencies then build and run the geospark/java/main/Example on
Spark 2.2.1 
Scala 2.11.12 
Java 64bit 1.8._151
Exception in thread "main" java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapred.FileInputFormat
	at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:312)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:199)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1.apply(RDD.scala:1115)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.aggregate(RDD.scala:1108)
	at org.apache.spark.api.java.JavaRDDLike$class.aggregate(JavaRDDLike.scala:426)
	at org.apache.spark.api.java.AbstractJavaRDDLike.aggregate(JavaRDDLike.scala:45)
	at org.datasyslab.geospark.spatialRDD.SpatialRDD.analyze(SpatialRDD.java:430)
	at org.datasyslab.geospark.spatialRDD.SpatialRDD.analyze(SpatialRDD.java:404)
	at org.datasyslab.geospark.spatialRDD.PointRDD.<init>(PointRDD.java:300)
	at example.Example.testSpatialRangeQuery(Example.java:156)
	at example.Example.main(Example.java:128)

**Comment by jiayuasu** [comment]
Read this and make sure you understand the dependency scope correctly: http://datasystemslab.github.io/GeoSpark/download/project/#package-the-project

**Comment by YaboSun** [comment]
@jiayuasu You mean I shouldn't configure anything and import the template project directly as maven model to run in IDEA ? 
And if I want to run it in cluster mode, I should package and change the dependency scope ,am I right?
Well,
1、 I uninstall my old IDEA and delete its configuration files
2、then import the geospark/java projects as maven model and do nothing 
3、finally build and run java/main/Example 
It doesn't work,and I get the same error.I haven't run it on Spark cluster ,just locally.I am not sure what I am doing wrong

**Comment by jiayuasu** [comment]
@YaboSun I just noticed that, running the template project in some Intelij IDEA versions may throw errors. Because IDEA has different conflict omitting strategies over versions. The root reason of all these errors are the conflicts of Spark's internal dependencies.

I have tried my best to manually fix some famous Spark dependency conflicts. Please pull the latest template project. At least in my IDEA (Ultimate, 2017.3), all projects work properly.

**Comment by YaboSun** [comment]
@jiayuasu All GeoSpark DEMOs passed！！！ Thanks very much for taking the time.
