### ISSUE TITLE
Having trouble with the GeoSpark-analysis template project

### ISSUE THREAD

**Issue by ytSong74** [jiayuasu/GeoSparkTemplateProject#8]
Hi, I am trying to run the template analysis project on a YARN cluster. But it fails all the time, with a error information like this:

INFO yarn.Client: 
	 client token: N/A
	 diagnostics: User class threw exception: java.lang.NoSuchMethodError: org.hsqldb.DatabaseURL.parseURL(Ljava/lang/String;ZZ)Lorg/hsqldb/persist/HsqlProperties;
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDataSource.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDataSource.getConnection(Unknown Source)
	at org.geotools.referencing.factory.epsg.DirectEpsgFactory.getConnection(DirectEpsgFactory.java:3302)
	at org.geotools.referencing.factory.epsg.ThreadedEpsgFactory.createBackingStore(ThreadedEpsgFactory.java:436)
	at org.geotools.referencing.factory.DeferredAuthorityFactory.getBackingStore(DeferredAuthorityFactory.java:133)
	at org.geotools.referencing.factory.BufferedAuthorityFactory.isAvailable(BufferedAuthorityFactory.java:235)
	at org.geotools.referencing.factory.DeferredAuthorityFactory.isAvailable(DeferredAuthorityFactory.java:119)
	at org.geotools.factory.FactoryRegistry.isAvailable(FactoryRegistry.java:667)
	at org.geotools.factory.FactoryRegistry.isAcceptable(FactoryRegistry.java:501)
	at org.geotools.factory.FactoryRegistry$1.filter(FactoryRegistry.java:192)
	at javax.imageio.spi.FilterIterator.advance(ServiceRegistry.java:821)
	at javax.imageio.spi.FilterIterator.<init>(ServiceRegistry.java:815)
	at javax.imageio.spi.ServiceRegistry.getServiceProviders(ServiceRegistry.java:516)
	at org.geotools.factory.FactoryRegistry.getServiceProviders(FactoryRegistry.java:197)
	at org.geotools.referencing.ReferencingFactoryFinder.getFactories(ReferencingFactoryFinder.java:180)
	at org.geotools.referencing.ReferencingFactoryFinder.getCRSAuthorityFactories(ReferencingFactoryFinder.java:455)
	at org.geotools.referencing.DefaultAuthorityFactory.getBackingFactory(DefaultAuthorityFactory.java:89)
	at org.geotools.referencing.DefaultAuthorityFactory.<init>(DefaultAuthorityFactory.java:69)
	at org.geotools.referencing.CRS.getAuthorityFactory(CRS.java:263)
	at org.geotools.referencing.CRS.decode(CRS.java:525)
	at org.geotools.referencing.CRS.decode(CRS.java:453)
	at org.datasyslab.geospark.spatialRDD.SpatialRDD.CRSTransform(SpatialRDD.java:175)
	at ScalaExample$.visualizeSpatialColocation(ScalaExample.scala:58)
	at ScalaExample$.delayedEndpoint$ScalaExample$1(ScalaExample.scala:33)
	at ScalaExample$delayedInit$body.apply(ScalaExample.scala:18)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at ScalaExample$.main(ScalaExample.scala:18)
	at ScalaExample.main(ScalaExample.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:688)

I think this can be a version problem, but I don't know how to deal with it. I will be appreciated if you can help me. The only changes I have made this the template is the change of Spark version and the sbt version. Here are the version settings in my build.sbt. Thanks a lot.

val SparkVersion = "2.3.0"

val SparkCompatibleVersion = "2.3"

val HadoopVersion = "2.7.2"

val GeoSparkVersion = "1.1.3"

**Comment by ytSong74** [comment]
@jiayuasu  Hi thank you for your reply. But I still have that problem. My sbt file now looks like this:
```
val SparkVersion = "2.3.0"

val SparkCompatibleVersion = "2.3"

val HadoopVersion = "2.7.2"

val geotoolsVersion = "17.0"

val GeoSparkVersion = "1.1.3"

val dependencyScope = "provided"

logLevel := Level.Warn

logLevel in assembly := Level.Error

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % SparkVersion % dependencyScope exclude("org.apache.hadoop", "*"),
  "org.apache.spark" %% "spark-sql" % SparkVersion % dependencyScope exclude("org.apache.hadoop", "*"),
  "org.apache.hadoop" % "hadoop-mapreduce-client-core" % HadoopVersion % dependencyScope,
  "org.apache.hadoop" % "hadoop-common" % HadoopVersion % dependencyScope,
  "org.datasyslab" % "geospark" % GeoSparkVersion,
  "org.datasyslab" % "geospark-sql_".concat(SparkCompatibleVersion) % GeoSparkVersion ,
  "org.datasyslab" % "geospark-viz" % GeoSparkVersion  


)
libraryDependencies ++= Seq(
  "org.geotools" % "gt-main" % geotoolsVersion,
  "org.geotools" % "gt-epsg-hsql" % geotoolsVersion,
  "org.geotools" % "gt-referencing" % geotoolsVersion,
  "org.geotools" % "gt-epsg-extension" % geotoolsVersion,
  "org.geotools" % "gt-shapefile" % geotoolsVersion,
  "javax.media" % "jai_core" % "1.1.3" from "http://download.osgeo.org/webdav/geotools/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar",
  "javax.media" % "jai_codec" % "1.1.3" from "http://download.osgeo.org/webdav/geotools/javax/media/jai_codec/1.1.3/jai_codec-1.1.3.jar",
  "javax.media" % "jai_imageio" % "1.1" from "http://download.osgeo.org/webdav/geotools/javax/media/jai_imageio/1.1/jai_imageio-1.1.jar"
)
```
Is there anything wrong with it? I am using sbt1.2.8.

**Comment by jiayuasu** [comment]
@ytSong74 
Please make sure you include all these strategies:
https://github.com/jiayuasu/GeoSparkTemplateProject/blob/master/geospark-analysis/build.sbt#L41

Then please use `sbt clean assembly` to package the jar.

After that, please unzip the jar and check whether geo-tools folders are there.

**Comment by pedromorfeu** [comment]
@ytSong74, did you manage to fix this?

**Comment by ytSong74** [comment]
@pedromorfeu Sorry, I haven't worked on this for a while. Thank you for your solution!
